version: '3.2'

services:

  chromedriver:
    image: selenium/standalone-chrome:3.141.59-oxygen
    container_name: wpbrowser_chromedriver
    links:
      - wp
    extra_hosts:
      - "wp.test:${WP_CONTAINER_IP:-127.0.0.1}"
    ports:
      - "4445:4444"

  db:
    image: mariadb:latest
    container_name: wpbrowser_db
    ports:
      # listen for external connections on port 3306
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: wp_site
      MYSQL_USER: wordrpess
      MYSQL_PASSWORD: wordpress
    command: mysqld --debug-no-sync

  wp:
    image: wordpress:php${PHP_VERSION:-5.6}-apache
    container_name: wpbrowser_wp
    depends_on:
      - db
    ports:
      # listen for external connections on port 3306
      - "80:80"
    environment:
      WORDPRESS_DB_NAME: wp_site
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
    volumes:
      # bind the core WordPress folder to the /var/www/html folder
      - ./../wordpress:/var/www/html
      # bind the root folder to the /project folder
      - ./..:/project

  waiter:
    image: martin/wait
    depends_on:
      - db
    environment:
      - db_TCP=tcp://db:3306
